name: Terraform CI/CD Pipeline for Smartwyre Platform Engineer Assessment

on:
  push:
    branches:
      - develop

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Azure Login
      uses: azure/login@v2
      with:
        credentials: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.10.3
      
    - name: Initialise
      run: terraform init

    - name: Validate
      run: terraform validate

    - name: Plan
      run: terraform plan

    - name: Apply
      run: terraform apply -auto-approve