name: Terraform CI/CD Pipeline for Smartwyre Cloud Engineer Assessment

on:
  push:
    branches:
      - develop

env:
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  RESOURCE_GROUP: "CloudOps-Smartwyre-terraform-backend-group"
  STORAGE_ACCOUNT: "smartwyreterraformstate"
  CONTAINER_NAME: "tfstate"

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.10.3

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Ensure Storage Account Exists
      run: |
        if ! az storage account show --name $STORAGE_ACCOUNT --resource-group $RESOURCE_GROUP &> /dev/null; then
          echo "Creating backend storage account..."
          az group create --name $RESOURCE_GROUP --location "Uk South"
          az storage account create --name $STORAGE_ACCOUNT --resource-group $RESOURCE_GROUP --location "UK South" --sku Standard_LRS
          az storage container create --name $CONTAINER_NAME --account-name $STORAGE_ACCOUNT
          az storage account blob-service-properties update --resource-group $RESOURCE_GROUP --account-name $STORAGE_ACCOUNT --enable-versioning true
        else
          echo "Storage account already exists."
        fi
      
    - name: Terraform Initialise
      run: terraform init

    - name: Terraform Format
      run: terraform fmt

    - name: Setup TFLint
      run: |
        curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash

    - name: Run TFLint
      run: tflint --init && tflint --format compact

    - name: Terraform Validate
      run: terraform validate

    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@v2
      with:
        projectBaseDir: .
        args: >
          -Dsonar.organization=smartwyre-interview
          -Dsonar.projectKey=function-app
          -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.token=${{ secrets.SONAR_TOKEN }}

    - name: Terraform Plan
      run: terraform plan

    - name: Terraform Apply
      run: terraform apply -auto-approve
